os: linux
dist: focal
language: python


services:
  - docker

env:
  COMPOSE_VERSION: 1.26.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - cp .env.dist .env
  - docker-compose up -d --build web

script:
  - docker-compose exec web invoke tests --path ''
  - docker-compose exec web flake8
